---
- name: Disable Fastest Mirror feature
  ini_file:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    section: main
    option: fastestmirror
    value: 0

- name: Configure DNF proxy
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: proxy
    value: "{{ pkg_proxy_url }}"
