---
- name: Disable Fastest Mirror plugin
  ini_file:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    section: main
    option: enabled
    value: 0

- name: Configure YUM proxy
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ pkg_proxy_url }}"
